### PR TITLE
test: test suite for user requests

### PR DESCRIPTION
**Pull request by GeekSilver**
## Description
This is a test suite for the following open issues.

- [Sign up] User can register to the platform
- [Log in] User can login to the platform once they submit their credentials
- [Profile update] User can alter their username, email and password
- [Account deletion] User can delete their account 

It contains tests to test if the issues are fixed.

This requires the following new dependencies.

- "mongodb-memory-server":  "^6.5.2"

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation

### CODE REVIEW

**Review by Makavura — APPROVED** [review]
Well documented code and comprehensive changes

**Review by AllanMwirigi — APPROVED** [review]

**Review by collengine — COMMENTED** [review]
well arranged

**Review by collengine — APPROVED** [review]
well arranged

**Comment by collengine** [comment]
approved the changes

**Pull request merged**
